spring:
    application:
        name: VkGrpcCRUD
    data:
        tarantool:
            host: ${TARANTOOL_HOST:localhost}
            port: ${TARANTOOL_PORT:3301}
            username: ${TARANTOOL_USERNAME:admin}
            password: ${TARANTOOL_PASSWORD:password}

grpc:
    server:
        port:
            ${GRPC_SERVER_PORT:9091}

